#
# Conda-forge friendly recipe fo AdoptOpenJDK OpenJDK builds.
#
# See the original at:
#   https://github.com/conda-forge/openjdk-feedstock
# Differences:
#   - We do not maintain ppc64le or aarch64 builds (should be trivial to bring back)
#   - We settle to use AdoptOpenJDK as only distribution
#   - In linux and mac we put the openjdk in a segregated directory to avoid hurdles like:
#     https://github.com/conda-forge/openjdk-feedstock/pull/60
#     Note this then makes libs, includes not be immediately available.
#     If this is a problem, we can revise the decision.
#   - We do not ship dejavu fonts - likely these would be better having their own package:
#     https://github.com/conda-forge/openjdk-feedstock/pull/1
#   - In linux and macos, we distribute the whole JDK, including demos
# TODOs:
#   - Coordinate also with JRE recipe (maybe)
#   - Create a dejavu-fonts package
#   - Segregate also windows package to its own dir (see qupath recipe) or revert the change for unix
# Notes:
#   - About support and LTSness:
#     https://adoptopenjdk.net/support.html
#

{% set name = "openjdk" %}
{% set version = "14" %}
{% set build_major = "14" %}
{% set build_minor = "36" %}
{% set build_plus = build_major + "+" + build_minor %}
{% set build_under = build_major + "_" + build_minor %}
{% set build_number = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:

  - url: https://github.com/AdoptOpenJDK/openjdk{{ build_major }}-binaries/releases/download/jdk-{{ build_plus }}/OpenJDK{{ build_major }}U-jdk_x64_linux_hotspot_{{ build_under }}.tar.gz   # [linux64]
    sha256: 6c06853332585ab58834d9e8a02774b388e6e062ef6c4084b4f058c67f2e81b5  # [linux64]
    folder: openjdk  # [linux64]

  - url: https://github.com/AdoptOpenJDK/openjdk{{ build_major }}-binaries/releases/download/jdk-{{ build_plus }}/OpenJDK{{ build_major }}U-jdk_x64_mac_hotspot_{{ build_under }}.tar.gz   # [osx]
    sha256: aabc3aebb0abf1ba64d9bd5796d0c7eb7239983f6e4c0f015b5b88be5616e4bd  # [osx]
    folder: openjdk  # [macos]

  - url: https://github.com/AdoptOpenJDK/openjdk{{ build_major }}-binaries/releases/download/jdk-{{ build_plus }}/OpenJDK{{ build_major }}U-jdk_x64_windows_hotspot_{{ build_under }}.tar.gz   # [win64]
    sha256: 9d8351a26c28498bdfe56e54545263588132c51954a4e8811d72bc9a8933afd6  # [win64]

build:
  number: {{ build_number }}

  # Could this be necessary?
  # See https://conda.io/projects/conda-build/en/latest/resources/define-metadata.html#binary-relocation
  # Java is working fine without relocation, but seems to choke if conda messes around these shared objects
  # binary_relocation: False

  script:
    # --- unix
    - mkdir -p ${PREFIX}/opt                             # [unix]
    - mv openjdk ${PREFIX}/opt/openjdk-{{ build_plus }}  # [unix]
    - cd ${PREFIX}/opt                                   # [unix]
    - ln -s openjdk-{{ build_plus }} openjdk             # [unix]
    - cd ${PREFIX}/bin                                   # [unix]
    - ln -s ../opt/openjdk/bin/* .                       # [unix]
    - mkdir -p "${PREFIX}"/etc/conda/activate.d                                                              # [unix]
    - cp "${RECIPE_DIR}/scripts/activate.sh" "${PREFIX}/etc/conda/activate.d/${PKG_NAME}_activate.sh"        # [unix]
    - mkdir -p "${PREFIX}"/etc/conda/deactivate.d                                                            # [unix]
    - cp "${RECIPE_DIR}/scripts/deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/${PKG_NAME}_deactivate.sh"  # [unix]

requirements:
  build:
  host:
    - alsa-lib        # [linux]
    - vs2013_runtime  # [win]
  run:
    - xorg-libx11                                        # [linux]
    - xorg-libxext                                       # [linux]
    - xorg-libxtst                                       # [linux]
    - xorg-libxrender                                    # [linux]
    - xorg-libxi                                         # [linux]
    - {{ pin_compatible("alsa-lib", max_pin="x.x.x") }}  # [linux]
    - vs2013_runtime                                     # [win]

test:
  requires:
    - {{ compiler('c') }}  # [not win]
  files:
    - test-jni     # [not win]
    - test-jni.sh  # [not win]
    - test-nio
  commands:
    - java -version
    - ./test-jni.sh  # [not win]

about:
  home: https://openjdk.java.net
  license: GPL-2.0
  license_family: GPL
  license_file:
    - LICENSE
  summary: An open-source implementation of the JDK   # [linux]
  description: >
    AdoptOpenJDK uses infrastructure, build and test scripts to produce
    prebuilt binaries from OpenJDK™ class libraries and a choice of either
    the OpenJDK HotSpot or Eclipse OpenJ9 VM.
    All AdoptOpenJDK binaries and scripts are open source licensed and available for free.

extra:
  recipe-maintainers:
    - sdvillal
  conda-forge-recipe-maintainers:
    - johanneskoester
    - sodre
    - mingwandroid
    - hadim
    - CJ-Wright
